name: 'IndexNow'
on:
  workflow_dispatch:
  schedule:
    # Set the schedule time
    - cron: '0 16 * * *'

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v3
        with:
          sitemap-location: 'https://leidun.pp.ua/sitemap.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
